package bean;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamReader;
import javax.xml.stream.XMLStreamWriter;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ListeAssociation {
	private List<Association> list = new ArrayList<Association>();
	private String theme;
	private int niveau;
	private int type;
	private String question;
	private List<String> exemple=ex();;
	private static File file=file();

	public List<String> ex(){
		List<String> list=new ArrayList<String>();
		for(int i=0;i<5;i++) {
			list.add(" ");
		}
		return list;
	}
	public static File file() {
		File file2= new File(System.getProperty("user.home") + File.separator + "xml"
				+ File.separator + "Asso.xml");
		if(!file2.isFile()) {
			file2=new File(System.getProperty("user.home") + File.separator + "Desktop" + File.separator+"xml"+File.separator
					+  "Asso.xml");
		} 
		return file2;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public List<String> getExemple() {
		return exemple;
	}
	public void setExemple(List<String> exemple) {
		this.exemple = exemple;
	}
	public List<Association> getList() {
		return list;
	}

	public void setList(List<Association> list) {
		this.list = list;
	}

	public String getTheme() {
		return theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public int getNiveau() {
		return niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public static List<ListeAssociation> ListCr() {
		ListeAssociation lasso = new ListeAssociation();
		List<ListeAssociation> list = new ArrayList<ListeAssociation>();
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Capitale");
		lasso.setType(1);
		lasso.setQuestion("Pays");
		lasso.getExemple().set(0, "Russie");
		lasso.getExemple().set(1, "Minsk");
		lasso.getExemple().set(2, "Moscou");
		lasso.getExemple().set(3, "Moscou");
		lasso.getExemple().set(4, "Moscou est bien la capitale de la Russie alors que Minsk est celle de la Bi�lorussie");
		Association asso = new Association();
		asso.AssoCr("France", "Paris", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Allemagne", "Berlin", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Espagne", "Madrid", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Italie", "Rome", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume-Uni", "Londres", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Suisse", "Berne", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Irlande", "Dublin", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pologne", "Varsovie", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Autriche", "Vienne", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Danemark", "Copenhague", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Su�de", "Stockholm", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Finlande", "Helsinki", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Norv�ge", "Oslo", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Gr�ce", "Ath�nes", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Chypre", "Nicosie", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Malte", "La Valette", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Portugal", "Lisbonne", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Serbie", "Belgrade", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�publique Tch�que", "Prague", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ukraine", "Kiev", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Peinture");
		lasso.setType(2);
		lasso.setQuestion("Tableau");
		lasso.getExemple().set(0, "img/Raphael.jpg");
		lasso.getExemple().set(1, "Raphael");
		lasso.getExemple().set(2, "Jerome Bosch");
		lasso.getExemple().set(3, "Raphael");
		lasso.getExemple().set(4, "le 'Mariage de la Vierge' est un tableau de Raphael");
		asso = new Association();
		asso.AssoCr("img/Joconde.jpg", "De Vinci", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/EO.jpg", "Courbet", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/NV.jpg", "Boticelli", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/EA.jpg", "Van Eyck", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/DVT.jpg", "Turner", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/TB.jpg", "Bruegel l'Ancien", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/Soulages.jpg", "Soulages", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/Guernica.jpg", "Picasso", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/PM.jpg", "Dali", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/RdN.jpg", "Rembrandt", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/MdG.jpg", "Poussin", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/JD.jpg", "Michel-Ange", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/Venise.jpg", "Canaletto", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/BM.jpg", "Berthe Morisot", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/VVG.jpg", "Van Gogh", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/JRB.jpg", "Kandinsky", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/gAb.jpg", "Klein", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/CPP.jpg", "Magritte", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/CM.jpg", "Monet", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("img/DdC.jpg", "Renoir", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(3);
		lasso.setTheme("Drapeaux");
		lasso.setType(3);
		lasso.setQuestion("Pays");
		lasso.getExemple().set(0, "Vatican");
		lasso.getExemple().set(1, "img/Chypre.png");
		lasso.getExemple().set(2, "img/Vatican.png");
		lasso.getExemple().set(3, "img/Vatican.png");
		lasso.getExemple().set(4, "ce drapeau est bien celui du Vatican alors que l'autre est celui de Chypre.");
		asso = new Association();
		asso.AssoCr("Belize", "img/Belize.png", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Suriname", "img/Suriname.png", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Eswatini", "img/Eswatini.png", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Nauru", "img/Nauru.png", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Seychelles", "img/Seychelles.png", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mongolie", "img/Mongolie.png", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Saint-Marin", "img/SM.png", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Comores", "img/Comores.png", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bahamas", "img/Bahamas.png", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sri Lanka", "img/SL.jpg", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Nepal", "img/Nepal.png", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Papouasie Nouvelle-Guin�e", "img/PNG.png", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Nicaragua", "img/Nicaragua.png", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Liechtenstein", "img/Liech.png", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Moldavie", "img/Moldavie.png", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Brune�", "img/Brunei.png", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pays de Galles", "img/PDG.png", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Lesotho", "img/Lesotho.png", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Malawi", "img/Malawi.png", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Kiribati", "img/Kiribati.png", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Capitale");
		lasso.setType(1);
		lasso.setQuestion("Capitale");
		lasso.getExemple().set(0, "Alger");
		lasso.getExemple().set(1, "Algerie");
		lasso.getExemple().set(2, "Tunisie");
		lasso.getExemple().set(3, "Algerie");
		lasso.getExemple().set(4, "Alger est bien la capitale de l'Algerie alors que pour la Tunisie c'est Tunis");
		asso = new Association();
		asso.AssoCr("Washington", "Etats-Unis", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("P�kin", "Chine", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Canberra", "Australie", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pr�toria", "Afrique du Sud", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("New Dehli", "Inde", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Moscou", "Russie", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Le Caire", "Egypte", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Buenos Aires", "Argentine", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Rabat", "Maroc", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Montevideo", "Uruguay", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Tirana", "Albanie", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ottawa", "Canada", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Wellington", "Nouvelle-Z�lande", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Brasilia", "Br�sil", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Lima", "P�rou", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("La Havane", "Cuba", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mexico", "Mexique", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Dakar", "S�n�gal", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bamako", "Mali", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Yaound�", "Cameroun", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Dates Historiques");
		lasso.setType(1);
		lasso.setQuestion("Date");
		lasso.getExemple().set(0, "1989");
		lasso.getExemple().set(1, "Crise des Missiles de Cuba");
		lasso.getExemple().set(2, "Chute du Mur de Berlin");
		lasso.getExemple().set(3, "Chute du Mur de Berlin");
		lasso.getExemple().set(4, "la chute du mur a bien eu lieu en 89 alors que la crise des missiles s'est produite en 62");
		asso = new Association();
		asso.AssoCr("1515", "Bataille de Marignan", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1941", "Pearl Harbour", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1914", "Assassinat de l'archiduc Fran�ois-Ferdinand � Sarajevo", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1789", "Prise de la Bastille", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("-44", "Assassinat de Jules C�sar", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1492", "D�couverte de l'Am�rique par Colomb", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1453", "Prise de Constantinople par les Ottomans", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1598", "Edit de Nantes", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("-1333", "Mort de N�fertiti", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1981", "Premi�re Election de Fran�ois Mitterand", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1815", "Bataille de Waterloo", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1066", "Victoire de Guillaume le Conqu�rant � Hastings", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("800", "Sacre de Charlemagne", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1099", "Prise de J�rusalem par les Crois�s", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1936", "Cong�s pay�s en France", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1337", "D�but de la guerre de Cent ans", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1163", "D�but de la construction de Notre-Dame de Paris", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("2001", "Attentats du 11 Septembre", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("2008", "Election de Barack Obama", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1851", "Coup d'Etat de Napoleon III", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(3);
		lasso.setTheme("Dates Historiques (Batailles)");
		lasso.setType(1);
		lasso.setQuestion("Bataille");
		lasso.getExemple().set(0, "Stalingrad");
		lasso.getExemple().set(1, "1942-1943");
		lasso.getExemple().set(2, "1970");
		lasso.getExemple().set(3, "1942-1943");
		lasso.getExemple().set(4, "la bataille de Stalingrad est un �pisode d�cisif de la seconde guerre mondiale (39-45)");
		asso = new Association();
		asso.AssoCr("Teutobourg", "9", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Qadesh", "-1274", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("El Alamein", "1942", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Verdun", "1916", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Gergovie", "-52", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Actium", "-31", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Poitiers", "732", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Stamford Bridge", "1066", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Normandie", "1944", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Di�n Bi�n Phu", "1954", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cr�cy", "1346", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bouvines", "1214", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Castillon", "1453", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Tenochtitlan", "1521", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pont d'Arcole", "1796", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Trafalgar", "1805", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Invincible Armada", "1588", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Falklands", "1914", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Gettysburg", "1863", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Lexington et Concord", "1775", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("H�ros de S�rie");
		lasso.setType(1);
		lasso.setQuestion("S�rie");
		lasso.getExemple().set(0, "24h Chrono");
		lasso.getExemple().set(1, "Jack Bauer");
		lasso.getExemple().set(2, "Flynn Carson");
		lasso.getExemple().set(3, "Jack Bauer");
		lasso.getExemple().set(4, "Jack Bauer est bien le h�ros de 24h Chrono alors que Flynn Carson est le h�ros de 'The Librarians'");
		asso = new Association();
		asso.AssoCr("Amicalement Votre", "Brett Sinclair et Danny Wilde", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mentalist", "Patrick Jane", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("The Rookie", "John Nolan", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("NCIS", "Leroy Jethro Gibbs", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Camping Paradis", "Tom Delorme", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Alias", "Sydney Bristow", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bones", "Temp�rance Brennan et Seeley Booth", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Agence Tout Risque", "Hannibal Smith", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Section de Recherche", "Martin Bernier", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Blue Bloods", "Franck Reagan", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Rookie Blue", "Andy McNally", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("The Listener", "Tobby Logan", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Elementary", "Sherlock Holmes et Joan Watson", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Grey's Anatomy", "Meredith Grey", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Friends", "Monica et Ross Geller", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Urgences", "Doug Ross", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Alert Cobra", "Semir Gersan", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Papa Schultz", "Robert Hogan", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Arrow", "Oliver Queen", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Supergirl", "Kara Danvers/Zor-El", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("B�timent Embl�matique/ Pays");
		lasso.setType(1);
		lasso.setQuestion("B�timent");
		lasso.getExemple().set(0, "Grande Muraille");
		lasso.getExemple().set(1, "Japon");
		lasso.getExemple().set(2, "Chine");
		lasso.getExemple().set(3, "Chine");
		lasso.getExemple().set(4, "la Grande Muraille de Chine");
		asso = new Association();
		asso.AssoCr("Pyramide de Mykerinos", "Egypte", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Colis�e", "Italie", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Porte de Brandenbourg", "Allemagne", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Parth�non", "Gr�ce", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Tour Eiffel", "France", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sagrada Familia", "Espagne", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire State Building", "Etats-Unis", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Machu Pichu", "P�rou", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Nid d'Oiseau", "Chine", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Angkor", "Cambodge", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mosqu�e Sainte-Sophie", "Turquie", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Krak des Chevaliers", "Syrie", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Op�ra de Sydney", "Australie", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Statue de la Petite Sir�ne", "Danemark", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Big Ben", "Royaume-Uni", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Tour CN", "Canada", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Kremlin", "Russie", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Maracan�", "Br�sil", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pont du 25 Avril", "Portugal", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Palais Imp�rial de Tokyo", "Japon", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Type de R�cits");
		lasso.setType(1);
		lasso.setQuestion("D�finition");
		lasso.getExemple().set(0, "R�cit de la vie de l'auteur avec des ajouts invent�s");
		lasso.getExemple().set(1, "Autofiction");
		lasso.getExemple().set(2, "Manga");
		lasso.getExemple().set(3, "Autofiction");
		lasso.getExemple().set(4, "autofiction vient de auto : soi-m�me et fiction : invent�");
		asso = new Association();
		asso.AssoCr("Univers avec des avanc�es scientifiques par rapport � notre �poque", "Science-Fiction", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Modification d'un �v�nement historique pour cr�er une r�alit� alternative", "Uchronie", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Univers invent� correspondant en g�n�ral � l'�poque m�dievale avec la pr�sence de la magie",
				"Heroic-Fantasy", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�cit de la vie de quelqu'un", "Biographie", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�cit de la vie de l'auteur", "Autobiographie", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Echange de courriers r�uni en une seule oeuvre", "Roman Epistolaire", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr(
				"Histoire se passant � une �poque ayant exist� mais avec � la fois des personnages ayant vraiment exist� et d'autres invent�s",
				"Fiction Historique", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�cit court", "Nouvelle", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Histoire tournant autour d'une enqu�te", "Polar", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Utopie qui satisfait une �lite et �loigne le bonheur de la majorit� ", "Dystopie", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Histoire se passant apr�s un �v�nement qui aurait grandement mis-�-mal l'humanit�",
				"Roman Post-Apocalyptique", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mani�re d'�crire en faisant attention au nombre de pieds et aux rimes", "Po�sie", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Histoire mettant en valeur un personnage en racontant ses aventures h�ro�ques", "Epop�e", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr(
				"R�cit se passant � notre �poque mais avec des �v�nements surnaturels comme la magie ou les esprits",
				"Fantastique", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�cit dont le but est faire peur au lecteur ou au spectateur", "Horreur", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Film se d�roulant durant l'antiquit�", "Peplum", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Film racontant la conqu�te de l'ouest", "Western", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�cit inspir� des bretteurs du XVII�me si�cle", "de Cape et d'�p�e", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Roman policier inscrit dans une r�alit� sociale, porteur d'un discours critique", "Roman Noir",
				19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Texte ou film visant � rendre compte de recherche ou de son opinion sur un th�me", "Essai", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Ecrivain et leur oeuvre");
		lasso.setType(1);
		lasso.setQuestion("Livre");
		lasso.getExemple().set(0, "Artemis Fowl");
		lasso.getExemple().set(1, "Eoin Colfer");
		lasso.getExemple().set(2, "Richard Castle");
		lasso.getExemple().set(3, "Eoin Colfer");
		lasso.getExemple().set(4, "Eoin Colfer est bien l'auteur de Artemis Fowl");
		asso = new Association();
		asso.AssoCr("Seigneur des Anneaux", "J.R.R. Tolkien", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("le Tr�ne de Fer", "G.R.R. Martin", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Harry Potter", "J.K. Rowling", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mort sur le Nil", "Agatha Christie", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Le Chien des Baskerville", "Arthur Conan Doyle", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Alice au Pays des Merveilles", "Lewis Carol", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Oliver Twist", "Charles Dickens", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Indignez-vous", "Stephane Hessel", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Si c'est un homme", "Primo Levi", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Le Monde de Narnia", "C.S. Lewis", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Hunger Games", "Suzanne Collins", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Divergente", "Veronica Roth", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Twilight", "Stephenie Meyer", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("James Bond", "Ian Fleming", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ivanho�", "Walter Scott", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("M�moire d'Outre-Tombe", "ChateauBriand", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Le Deuxi�me Sexe", "Simone de Beauvoir", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Germinal", "Emile Zola", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Les Mis�rables", "Victor Hugo", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("L'Assomoir", "Emile Zola", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(3);
		lasso.setTheme("Distance de Paris");
		lasso.setType(1);
		lasso.setQuestion("Kilom�trage � vol d'oiseau");
		lasso.getExemple().set(0, "1026");
		lasso.getExemple().set(1, "Paris-Copenhague");
		lasso.getExemple().set(2, "Paris-Qu�bec");
		lasso.getExemple().set(3, "Paris-Copenhague");
		lasso.getExemple().set(4, "Paris-Copenhague fait bien 1026 km alors que Paris-Qu�bec fait 5044 km");
		asso = new Association();
		asso.AssoCr("505", "Paris-Brest", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("212", "Paris-Roubaix", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("686", "Paris-Nice", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("17", "Paris-Versailles", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("660", "Paris-Marseille", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("878", "Paris-Berlin", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("9088", "Paris-Los Angeles", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("5790", "Paris-New York", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("16965", "Paris-Sydney", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("8686", "Paris-Pretoria", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("10965", "Paris-Montevideo", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("588", "Paris-Toulouse", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1079", "Paris-Zagreb", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("2392", "Paris-H�raklion", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("1349", "Paris-Alger", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("4207", "Paris-Dakar", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("343", "Paris-Londres", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("9715", "Paris-Tokyo", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("3210", "Paris-Le Caire", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("7785", "Paris-Paris(Texas)", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Duo H�ros/M�chant");
		lasso.setType(1);
		lasso.setQuestion("H�ros");
		lasso.getExemple().set(0, "Thor");
		lasso.getExemple().set(1, "Odin");
		lasso.getExemple().set(2, "Loki");
		lasso.getExemple().set(3, "Loki");
		lasso.getExemple().set(4, "Loki veut prendre la place de Thor aupr�s de Odin, p�re naturel de Thor et adoptif de Loki");
		asso = new Association();
		asso.AssoCr("Batman", "Joker", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Superman", "Lex Luthor", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sherlock Holmes", "Moriarty", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Professeur Xavier", "Magneto", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Oliver Queen", "Malcolm Merlyn", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Patrick Jane", "Red John", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Harry Potter", "Voldemort", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Luke Skywalker", "Palpatine", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Alejandro de la Vega", "Capitaine Monastorio", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Super Mario", "Bowser", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("D'Artagnan", "Richelieu", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Shrek", "Charmant", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Jack Sparrow", "Davy Jones", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("James Bond", "Spectre", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Frodon Sacquet", "Sauron", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Henry Morgan", "Adam", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Merlin", "Morgane", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Donatello", "Shredder", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Robin des Bois", "Jean sans Terre", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Jean Valjean", "Javert", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(3);
		lasso.setTheme("Dernier souverain d'un nom � r�gner");
		lasso.setType(1);
		lasso.setQuestion("Pays/R�le/Nom");
		lasso.getExemple().set(0, "France/Roi/Henri");
		lasso.getExemple().set(1, "VI");
		lasso.getExemple().set(2, "IV");
		lasso.getExemple().set(3, "IV");
		lasso.getExemple().set(4, "Henri IV est le dernier roi de France � s'�tre nomm� Henri");
		asso = new Association();
		asso.AssoCr("France/ Roi/ Louis", "XVIII", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Angleterre/ Roi/ Henri", "VIII", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Egypte/ Pharaon/ Cl�op�tre", "VII", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Vatican/ Pape/ Jean", "XXIII", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Espagne/ Reine/ Isabelle", "I", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Saint-Empire Romain Germanique/ Empereur/ Charles", "VII", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pi�mont-Sardaigne/ Roi/ Victor-Emmanuel", "II", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ecosse/ Roi/ Jacques", "VI", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Danemark/ Reine/ Margrethe", "II", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Portugal/ Roi/ Pierre", "IV", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Deux-Siciles/ Roi/ Ferdinand", "II", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Toscane/ Grand-Duc/ Cosme", "III", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Ottoman/ Sultan/ Moustapha", "IV", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Russe/ Tsar/ Ivan", "V", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Romain/ Empereur/ S�v�re", "III", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Normandie/ Duc/ Louis", "XVII", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Toulouse/ Comte/ Raymond", "IX", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("J�rusalem/ Roi/ Baudouin", "V", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Byzantin/ Empereur/ Constantin", "XI", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Venise/ Doge/ Domenico", "II", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Tableau de Mendele�ev");
		lasso.setType(1);
		lasso.setQuestion("Abr�viation");
		lasso.getExemple().set(0, "F");
		lasso.getExemple().set(1, "Fluor");
		lasso.getExemple().set(2, "Fer");
		lasso.getExemple().set(3, "Fluor");
		lasso.getExemple().set(4, "le fluor a bien pour symbole le f alors que le fer c'est fe");
		asso = new Association();
		asso.AssoCr("Au", "Or", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ag", "Argent", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("C", "Carbone", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cu", "Cuivre", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("K", "Potassium", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("O", "Oxyg�ne", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cl", "Chlore", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("H", "Hydrog�ne", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Mg", "Magnesium", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("He", "Helium", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Li", "Lithium", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Co", "Cobalt", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("U", "Uranium", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cs", "Cesium", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("I", "Iode", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("N", "Azote", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Na", "Sodium", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("S", "Souffre", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Y", "Yttrium", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("At", "Astate", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Sportifs Fran�ais");
		lasso.setType(1);
		lasso.setQuestion("Sportif");
		lasso.getExemple().set(0, "Fabien Barthez");
		lasso.getExemple().set(1, "Rugby");
		lasso.getExemple().set(2, "Football");
		lasso.getExemple().set(3, "Football");
		lasso.getExemple().set(4, "Fabien Barthez �tait le gardien de l'Equipe de France de football, championne du monde en 1998");
		asso = new Association();
		asso.AssoCr("Renaud Lavillenie", "Saut � la Perche", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Martin Fourcade", "Biathlon", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Jean-Claude Killy", "Ski Alpin", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Hugo Lloris", "Football", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Tony Parker", "Basket-Ball", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Nicola Karabatic", "Handball", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sebastien Chabal", "Rugby", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Vicnent Luis", "Triathlon", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Fran�ois Dhaene", "Ultra-Trail", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cristophe Lema�tre", "200m et 100m", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pauline Ferrand-Prevost", "VTT", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Camille Abily", "Football", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Laura Flessel", "Escrime", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Eunice Barber", "Heptathlon", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Laure Manaudou", "Natation", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Marie-Jos� P�rec", "400m et 200m", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Surya Bonaly", "Patinage Artistique", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("C�line Dumerc", "Basket-Ball", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Val�rie Nicolas", "Handball", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Alexandra Ledermann", "Equitation", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Les armes et leur type");
		lasso.setType(1);
		lasso.setQuestion("Arme");
		lasso.getExemple().set(0, "Fusil Sniper");
		lasso.getExemple().set(1, "Arme d'hast");
		lasso.getExemple().set(2, "Arme � feu");
		lasso.getExemple().set(3, "Arme � feu");
		lasso.getExemple().set(4, "le fusil sniper est une arme � feu � longue port�e");
		asso = new Association();
		asso.AssoCr("Mousquet", "Arme � Feu", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Braquemart", "Ep�e", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Katana", "Sabre", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Fleuret", "Arme d'Escrime", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Scorpion", "Engin de si�ge", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Onagre", "Engin de si�ge", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Poignard", "Arme de Jet", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Shuriken", "Arme de Jet", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Kuna�", "Arme de Jet", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Glaive", "Ep�e", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Rapi�re", "Ep�e", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Claymore", "Ep�e", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Cimeterre", "Sabre", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("K�pesh", "Sabre", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Hallebarde", "Arme d'Hast", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pique", "Arme d'Hast", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Vouge", "Arme d'Hast", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Revolver", "Arme � Feu", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("V2", "Fus�e", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Colt", "Arme � Feu", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(3);
		lasso.setTheme("Anciens Territoires et leur pays actuel");
		lasso.setType(1);
		lasso.setQuestion("Territoire");
		lasso.getExemple().set(0, "Duch� de Brabant");
		lasso.getExemple().set(1, "Pays-Bas/Belgique");
		lasso.getExemple().set(2, "Belgique/France");
		lasso.getExemple().set(3, "Pays-Bas/Belgique");
		lasso.getExemple().set(4, "ce duch� a �t� s�par� en deux entre les Provinces-Unis(Pays-Bas actuel) et le Saint-Empire(parti Belge)");
		asso = new Association();
		asso.AssoCr("Royaume de Pi�mont-Sardaigne", "Italie/France", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume de Navarre", "France/Espagne", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Union de Kalmar", "Danemark/Su�de/ Finlande/Norv�ge/ Islande", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Egypte Pharaonique", "Egypte/Soudan/ Palestine/Isra�l/ Syrie/Liban", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Egypte Fatimide", "Italie/Alg�rie/ Tunisie/Lybie/ Egypte/Arabie Saoudite/ Palestine/Isra�l/ Syrie/Liban", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume de Mac�doine (hors conqu�te d'Alexandre le Grand)", "Mac�doine du Nord/Gr�ce/ Bulgarie/Albanie", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Duch� de Normandie", "Royaume-Uni/France", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�publique de G�nes", "Italie/France", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Rus' de Kiev", "Ukraine/Russie/ Bi�lorussie/Lituanie/ Estonie/Finlande", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Horde d'Or", "Ukraine/Russie/ Kazakhstan/Bulgarie", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Saint-Empire Romain Germanique", "Allemagne/Italie/ Suisse/France/ Pologne/Autriche/ Belgique/Pays-bas/ Luxembourg/Slov�nie/ R�publique Tch�que", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empite Hittite", "Turquie/Liban/ Syrie", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Ligue de D�los", "Gr�ce/Turquie", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume Numide", "Alg�rie/Tunisie", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("R�publique de Venise", "Italie/Gr�ce/ Turquie/Chypre/ Albanie/Bosnie-Herz�govine/ Croatie/Slov�nie", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Byzantin", "Gr�ce/Turquie/ Albanie/Bulgarie/ Chypre/ Syrie/Liban/ Palestine/Isra�l/ Egypte/Lybie", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Incas", "P�rou/Bolivie/ Equateur/Colombie/ Argentine/Chili", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume d'Aragon", "Espagne", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume de Cal�donie", "Royaume-Uni", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Empire Songha�", "Mali/Niger/ Nigeria/Benin/ Burkina Faso/Guin�e/ S�n�gal/Gambie/ Mauritanie", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Li� par un 'et' (ou un '&')");
		lasso.setType(1);
		lasso.setQuestion("Premi�re Partie");
		lasso.getExemple().set(0, "Casse-toi, tu pues et");
		lasso.getExemple().set(1, "Marche � l'ombre");
		lasso.getExemple().set(2, "Va-ten");
		lasso.getExemple().set(3, "Marche � l'ombre");
		lasso.getExemple().set(4, "c'est un extrait de 'Marche � l'ombre' de Renaud");
		asso = new Association();
		asso.AssoCr("Laurel et", "Hardy", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Royaume de France et", "de Navarre", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sao Tom� et", "Principe", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Antigua et", "Barbuda", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Michel et", "Augustin", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Christine &", "the Queens", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Spirou et", "Fantasio", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Asterix et", "Ob�lix", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bonnie &", "Clyde", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Kate et", "William", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Harry Potter et", "la Chambre des Secrets", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Lexington et", "Concord", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Michel Fugain et", "le Big Bazar", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Jules C�sar et", "Cl�op�tre", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Guillaume et", "les Gar�ons � Table", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Pierre et", "Marie Curie", 16);
		lasso.getList().add(asso);
		asso = new Association();
		int a=(int)(Math.random()*6+1);
		String f=" ";
		switch(a) {
		case 1:
			f="Catherine d'Aragon";
			break;
		case 2:
			f="Ann Boleyn";
			break;
		case 3:
			f="Jeanne Seymour";
			break;
		case 4:
			f="Anne de Cl�ves";
			break;
		case 5:
			f="Catherine Howard";
			break;
		case 6:
			f="Catherine Parr";
			break;
		}
		asso.AssoCr("Henri VIII d'Angleterre et", f, 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Grande-Bretagne et", "Irlande du Nord", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Olive et", "Tom", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Aragorn et", "Arwen", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(1);
		lasso.setTheme("Si�ges d'Entreprises");
		lasso.setType(1);
		lasso.setQuestion("Entreprise");
		lasso.getExemple().set(0, "Nokia");
		lasso.getExemple().set(1, "Finlande");
		lasso.getExemple().set(2, "Su�de");
		lasso.getExemple().set(3, "Finalnde");
		lasso.getExemple().set(4, "le si�ge de Nokia est � Espoo en Finlande");
		asso = new Association();
		asso.AssoCr("Air Liquide", "France", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Air France", "France", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Michelin", "France", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("General Motors", "Etats-Unis", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Google", "Etats-Unis", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Oracle", "Etats-Unis", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Huawei", "Chine", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Honda", "Japon", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sony", "Japon", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Philips", "Pays-Bas", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bosch", "Allemagne", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Marks & Spencer", "Royaume-Uni", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Wallmart", "Etats-Unis", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Monsanto", "Etats-Unis", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Rai Uno", "Italie", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Schneider Electric", "France", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Airbus", "Pays-Bas", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Opel", "Allemagne", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Dacia", "Roumanie", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Bombardier Transport", "Allemagne", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		lasso = new ListeAssociation();
		lasso.setNiveau(2);
		lasso.setTheme("Pays des dirigeants actuels");
		lasso.setType(1);
		lasso.setQuestion("Chef d'Etat");
		lasso.getExemple().set(0, "Cyril Ramaphosa");
		lasso.getExemple().set(1, "Afrique du Sud");
		lasso.getExemple().set(2, "Nouvelle-Zelande");
		lasso.getExemple().set(3, "Afrique du Sud");
		lasso.getExemple().set(4, "Cyril Ramaphosa a bien �t� �lu pr�sident de l'Afrique du Sud alors que la premi�re ministre n�o-z�landaise est Jacinda Ardern");
		asso = new Association();
		asso.AssoCr("Emmanuel Macron", "France", 1);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Margrethe II", "Danemark", 2);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sergio Mattarella", "Italie", 3);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Donald Trump", "Etats-Unis", 4);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Elisabeth II", "Australie", 5);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Felipe VI", "Espagne", 6);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Frank-Walter Steinmeier", "Allemagne", 7);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Xi Jinping", "Chine", 8);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Willem-Alexander", "Pays-Bas", 9);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Harald V", "Norv�ge", 10);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Charles XVI Gustave", "Su�de", 11);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Jair Bolsonaro", "Br�sil", 12);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Naruhito", "Japon", 13);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Egils Levits", "Lettonie", 14);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Sauli Niinist�", "Finlande", 15);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Andr�s Manuel Lopez Obrador", "Mexique", 16);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Salom� Zourabichvili", "G�orgie", 17);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Recep Tayyip Erdogan", "Turquie", 18);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Vladimir Poutine", "Russie", 19);
		lasso.getList().add(asso);
		asso = new Association();
		asso.AssoCr("Salmane ben Abdelaziz Al Saoud", "Arabie Saoudite", 20);
		lasso.getList().add(asso);
		list.add(lasso);
		List<ListeAssociation> listxml=ListeAssociation.read();
		list.addAll(listxml);
		return list;
	}

	
	@Override
	public String toString() {
		return "ListeAssociation [type=" + type + ", theme=" + theme + ", niveau=" + niveau + ", question=" + question
				+ ", list=" + list + "]";
	}

	public static List<ListeAssociation> read() {
		List<ListeAssociation> listJ = new ArrayList<ListeAssociation>();
	
		XMLInputFactory factory = XMLInputFactory.newFactory();

		List<Integer> events = new ArrayList<Integer>();

		try {
			XMLStreamReader eye = factory.createXMLStreamReader(new InputStreamReader(new FileInputStream(file),Charset.forName("utf-8")));

			ListeAssociation joueur = null;
			int a = 0;
			int ex=0;
			while (eye.hasNext()) {
				int eventType = eye.next();

				if (!events.contains(eventType)) {
					events.add(eventType);
				}
				
				switch (eventType) {
				case XMLStreamReader.START_ELEMENT:
					
					switch (eye.getLocalName()) {
					case "Pseudos":

						break;
					case "Asso":
						
						joueur = new ListeAssociation();
						listJ.add(joueur);
						a=listJ.size()-1;
						
						for (int i = 0; i < eye.getAttributeCount(); i++) {
							
							switch (eye.getAttributeName(i).toString().toUpperCase()) {
							case "NIV":
								
								
								listJ.get(a).setNiveau(Integer.parseInt(eye.getAttributeValue(i)));
								
								break;
							case "TYPE":
								listJ.get(a).setType(Integer.parseInt(eye.getAttributeValue(i)));
								break;
							case "THEME":
								listJ.get(a).setTheme(eye.getAttributeValue(i));
								
								break;
							case "QUESTION":
								listJ.get(a).setQuestion(eye.getAttributeValue(i));
								break;
							
							
							
							}
						}
						break;
					case "QR":
						
						Association asso=new Association();
						asso.AssoCr(eye.getAttributeValue(2),eye.getAttributeValue(1) , Integer.parseInt(eye.getAttributeValue(0)));
						listJ.get(a).getList().add(asso);
						
						break;
					case "Exemple":
						
						listJ.get(a).getExemple().set(ex, eye.getAttributeValue(0));
						ex++;
						if(ex==5) {
							
							ex=0;
						}
						break;
						}
				
					
						break;
					}

					
				
				}

			

		} catch (Exception e) {
			e.getMessage();
		}
		return listJ;
	}

	public static void write(List<ListeAssociation> listeId) {
	
		
		if(!file.isFile()) {
			
			try {
				DocumentBuilderFactory dbFactory=DocumentBuilderFactory.newInstance();
				DocumentBuilder docBuilder=dbFactory.newDocumentBuilder();
				
				Document doc=docBuilder.newDocument();
				
				Element racine=doc.createElement("Association");
				doc.appendChild(racine);
				
				TransformerFactory tf=TransformerFactory.newInstance();
				Transformer t=tf.newTransformer();
				DOMSource source=new DOMSource(doc);
				StreamResult resultat=new StreamResult(file);
				
				t.transform(source, resultat);
			}catch(Exception e) {
				
			}
		}
		XMLOutputFactory factory = XMLOutputFactory.newFactory();

		
		try {
			FileOutputStream channel = new FileOutputStream(file);

			
			XMLStreamWriter pen = factory.createXMLStreamWriter(channel, "UTF-8");

			pen.writeStartDocument("UTF-8", "1.0");
			pen.writeCharacters("\r\n");
			pen.writeStartElement("Association");
			for (ListeAssociation identifiant : listeId) {
				pen.writeCharacters("\r\n\t");
				pen.writeStartElement("AssociationL");
				pen.writeCharacters("\r\n\t\t");
				pen.writeEmptyElement("Asso");
				pen.writeAttribute("Niv", (String.valueOf(identifiant.getNiveau())));
				pen.writeAttribute("Type", (String.valueOf(identifiant.getType())));
				pen.writeAttribute("Theme", identifiant.getTheme());
				pen.writeAttribute("Question", identifiant.getQuestion());
				pen.writeCharacters("\r\n\t\t");
				pen.writeStartElement("Liste");
				for(int i=0;i<identifiant.getList().size();i++) {
					pen.writeCharacters("\r\n\t\t\t");
					pen.writeEmptyElement("QR");
					pen.writeAttribute("ID", (String.valueOf(identifiant.getList().get(i).getId())));
					pen.writeAttribute("Reponse", identifiant.getList().get(i).getReponse());
					pen.writeAttribute("Question", identifiant.getList().get(i).getQuestion());
				}
				pen.writeCharacters("\r\n\t\t");
				pen.writeEndElement();
				pen.writeCharacters("\r\n\t\t");
				pen.writeStartElement("Exemples");
				for(int i=1;i<=5;i++) {
					pen.writeCharacters("\r\n\t\t\t");
					pen.writeEmptyElement("Exemple");
					pen.writeAttribute("Ex", (identifiant.getExemple().get(i-1)));
				}
				pen.writeCharacters("\r\n\t\t");
				pen.writeEndElement();
				pen.writeCharacters("\r\n\t");
				pen.writeEndElement();
			}
			
			pen.writeCharacters("\r\n");
			pen.writeEndElement();

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
